### ISSUE TITLE
Using javaslang library List as return type in controller causes StackOverflowError

### ISSUE THREAD

**Issue by kpirkkal** [EvidentSolutions/apina#33]
Javaslang library List as return type in controller causes apina to throw StackOverflowError.

Example of controller method causing error:

```
import javaslang.collection.List;

public List<String> exampleMethod() {...}
```

Stacktrace:

```
java.lang.StackOverflowError
	at fi.evident.apina.java.model.type.JavaType$Variable.hashCode(JavaType.kt:127)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at fi.evident.apina.java.model.type.TypeEnvironment.lookup(TypeEnvironment.kt:27)
	at fi.evident.apina.spring.JacksonTypeTranslator.translateType(JacksonTypeTranslator.kt:49)
```

Test to reproduce error

https://github.com/kpirkkal/apina/commit/ad27d827432c46224913c83f4bba4ab28802e265

**Comment by komu** [comment]
Released `0.7.2` with this fix.
